/**
 * File generated by component factory
 */
export interface GeneratedComponentFile {
	// Path relative to root
	filename: string;

	// Content
	content: string;
}

/**
 * Asset generated by component factory
 */
export interface GeneratedAssetFile extends GeneratedComponentFile {
	// Import path, relative to component file
	import: string;
}

/**
 * Generated component
 */
export interface FactoryGeneratedComponent {
	// Assets
	assets: GeneratedAssetFile[];

	// Main file content
	content: string;

	// Types filename (if any)
	types?: string;
}

/**
 * Component data with filename
 */
export interface FactoryComponent
	extends Omit<FactoryGeneratedComponent, 'ext' | 'forceExtension'> {
	// Icon name: 'name' or 'prefix/name'
	icon: string;

	// Component file name
	filename: string;
}
